import { Header } from '@/components/header'
import { Zap } from 'lucide-react'
import Link from 'next/link'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms of Service — IgualAI',
  description: 'Terms of Service for IgualAI',
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white dark:bg-neutral-950 flex flex-col">
      <Header />

      <main className="flex-1 max-w-3xl mx-auto w-full px-6 pt-32 pb-20">
        <h1 className="text-4xl font-bold text-neutral-900 dark:text-white mb-2">Terms of Service</h1>
        <p className="text-sm text-neutral-500 dark:text-neutral-400 mb-12">Last updated: April 27, 2026</p>

        <div className="prose-neutral space-y-10 text-neutral-700 dark:text-neutral-300 text-sm leading-relaxed">

          <section>
            <h2 className="text-lg font-semibold text-neutral-900 dark:text-white mb-3">1. Agreement to Terms</h2>
            <p>By accessing or using IgualAI ("Service", "we", "us", "our"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service. We reserve the right to modify these terms at any time. Continued use after changes constitutes acceptance.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-neutral-900 dark:text-white mb-3">2. Description of Service</h2>
            <p>IgualAI is an AI-powered website cloning tool that allows users to create editable replicas of publicly accessible web pages for purposes including design reference, prototyping, and educational study. The Service uses Claude AI (Anthropic) to reconstruct websites as self-contained HTML files.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-neutral-900 dark:text-white mb-3">3. Acceptable Use</h2>
            <p className="mb-3">You may use IgualAI only for lawful purposes and in accordance with these Terms. Permitted uses include:</p>
            <ul className="list-disc pl-5 space-y-1 mb-3">
              <li>Personal design reference and inspiration</li>
              <li>Prototyping and mockups for original projects</li>
              <li>Educational study of web design and development techniques</li>
              <li>Archiving your own websites or websites you have permission to copy</li>
              <li>Competitive research and market analysis (visual reference only)</li>
            </ul>
            <p>You are solely responsible for how you use the cloned output and for ensuring your use complies with all applicable laws, including copyright law.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-neutral-900 dark:text-white mb-3">4. Prohibited Content and Uses</h2>
            <p className="mb-3">You may not use IgualAI to:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>Clone websites for the purpose of phishing, fraud, or impersonation</li>
              <li>Reproduce, distribute, or publish cloned content in violation of the original site's copyright or terms of service</li>
              <li>Create or distribute malware, spyware, or other malicious software</li>
              <li>Scrape or harvest personal data from cloned pages</li>
              <li>Reproduce content that is defamatory, obscene, or illegal under applicable law</li>
              <li>Circumvent technical protection measures on any website</li>
              <li>Use the Service for any commercial purpose that directly infringes third-party intellectual property</li>
              <li>Attempt to overload, disrupt, or interfere with the Service or target websites</li>
              <li>Resell, sublicense, or make the Service available to third parties without our written consent</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-neutral-900 dark:text-white mb-3">5. Intellectual Property and Cloned Content</h2>
            <p className="mb-3">IgualAI is a tool. We do not review, endorse, or take responsibility for the content of websites you choose to clone. All intellectual property rights in the original website content remain with their respective owners.</p>
            <p className="mb-3">The AI-reconstructed output generated by IgualAI is provided "as generated." You acknowledge that:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>The cloned output may be a derivative work subject to the original site's copyright</li>
              <li>You are responsible for obtaining any necessary permissions before publishing or distributing cloned content</li>
              <li>IgualAI makes no claim of ownership over your cloned output</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-neutral-900 dark:text-white mb-3">6. DMCA Policy</h2>
            <p className="mb-3">IgualAI respects intellectual property rights and complies with the Digital Millennium Copyright Act (DMCA). If you believe that content stored on our platform infringes your copyright, please submit a written notice to us containing:</p>
            <ul className="list-disc pl-5 space-y-1 mb-3">
              <li>Your physical or electronic signature</li>
              <li>Identification of the copyrighted work you claim has been infringed</li>
              <li>Identification of the infringing material and its location on our Service</li>
              <li>Your contact information (name, address, email, phone number)</li>
              <li>A statement that you have a good-faith belief that the use is not authorized</li>
              <li>A statement, made under penalty of perjury, that the information is accurate and you are authorized to act on behalf of the copyright owner</li>
            </ul>
            <p>Upon receiving a valid DMCA notice, we will promptly remove or disable access to the identified content and notify the user who stored it. Repeat infringers will have their accounts terminated.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-neutral-900 dark:text-white mb-3">7. Disclaimer of Warranties</h2>
            <p className="mb-3">THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.</p>
            <p>We do not warrant that the Service will be uninterrupted, error-free, or free of viruses or other harmful components. We do not warrant the accuracy, completeness, or usefulness of any cloned output.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-neutral-900 dark:text-white mb-3">8. Limitation of Liability</h2>
            <p className="mb-3">TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, IGUALAI AND ITS OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS SHALL NOT BE LIABLE FOR:</p>
            <ul className="list-disc pl-5 space-y-1 mb-3">
              <li>Any indirect, incidental, special, consequential, or punitive damages</li>
              <li>Any damages arising from your use or inability to use the Service</li>
              <li>Any content obtained through the Service, including cloned website content</li>
              <li>Any claims by third parties related to your use of cloned content</li>
              <li>Copyright infringement claims arising from websites you choose to clone</li>
            </ul>
            <p>OUR TOTAL LIABILITY TO YOU FOR ALL CLAIMS SHALL NOT EXCEED THE AMOUNT YOU PAID TO US IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-neutral-900 dark:text-white mb-3">9. Indemnification</h2>
            <p>You agree to indemnify, defend, and hold harmless IgualAI and its officers, directors, employees, and agents from and against any claims, liabilities, damages, judgments, awards, losses, costs, expenses, or fees (including reasonable attorneys' fees) arising out of or relating to your use of the Service, your cloned content, or your violation of these Terms.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-neutral-900 dark:text-white mb-3">10. Termination</h2>
            <p className="mb-3">We reserve the right to suspend or terminate your account and access to the Service at our sole discretion, without notice, for conduct that we believe:</p>
            <ul className="list-disc pl-5 space-y-1 mb-3">
              <li>Violates these Terms</li>
              <li>Is harmful to other users, third parties, or the Service</li>
              <li>Involves fraudulent, deceptive, or illegal activity</li>
              <li>Results in repeated valid DMCA takedown notices</li>
            </ul>
            <p>Upon termination, your right to use the Service ceases immediately. Provisions that by their nature should survive termination will survive, including intellectual property, disclaimers, indemnification, and limitation of liability.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-neutral-900 dark:text-white mb-3">11. Governing Law and Dispute Resolution</h2>
            <p className="mb-3">These Terms are governed by and construed in accordance with the laws of the State of Delaware, United States, without regard to conflict of law principles.</p>
            <p>Any dispute arising from these Terms or your use of the Service shall first be attempted to be resolved through good-faith negotiation. If unresolved within 30 days, disputes shall be submitted to binding arbitration under the rules of the American Arbitration Association, conducted in English. You waive any right to a jury trial or to participate in a class action.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-neutral-900 dark:text-white mb-3">12. Miscellaneous</h2>
            <p className="mb-3">These Terms constitute the entire agreement between you and IgualAI regarding the Service. If any provision is found unenforceable, the remaining provisions remain in full force. Our failure to enforce any right or provision shall not be deemed a waiver. We may assign our rights and obligations under these Terms without restriction.</p>
          </section>

        </div>
      </main>

      <footer className="border-t border-neutral-100 dark:border-neutral-800/60 py-8 px-6 flex items-center justify-between text-xs text-neutral-400 dark:text-neutral-500">
        <div className="flex items-center gap-2">
          <Zap className="w-3 h-3" />
          <span>IgualAI</span>
        </div>
        <div className="flex items-center gap-6">
          <Link href="/terms" className="hover:text-neutral-600 dark:hover:text-neutral-300 transition-colors">Terms</Link>
          <Link href="/privacy" className="hover:text-neutral-600 dark:hover:text-neutral-300 transition-colors">Privacy</Link>
          <Link href="/acceptable-use" className="hover:text-neutral-600 dark:hover:text-neutral-300 transition-colors">Acceptable Use</Link>
        </div>
      </footer>
    </div>
  )
}
