import { NextRequest, NextResponse } from 'next/server'
import { auth } from '@clerk/nextjs/server'
import { createServiceClient } from '@/lib/supabase'

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { userId } = await auth()
    if (!userId) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

    const { id } = await params
    const supabase = createServiceClient()

    // Get user
    const { data: user } = await supabase
      .from('users')
      .select('id, plan')
      .eq('clerk_id', userId)
      .single()

    if (!user) return NextResponse.json({ error: 'User not found' }, { status: 404 })

    // Check download permission
    if (user.plan === 'free') {
      return NextResponse.json(
        { error: 'Upgrade to Starter or above to download projects', upgradeRequired: true },
        { status: 403 }
      )
    }

    // Get project
    const { data: project } = await supabase
      .from('projects')
      .select('*')
      .eq('id', id)
      .eq('user_id', user.id)
      .single()

    if (!project) return NextResponse.json({ error: 'Project not found' }, { status: 404 })

    // Create ZIP using JSZip
    const JSZip = (await import('jszip')).default
    const zip = new JSZip()

    // Add main HTML file
    zip.file('index.html', project.html_content)

    // Add a basic README
    zip.file(
      'README.md',
      `# ${project.name}\n\nCloned from: ${project.url}\n\nGenerated by CloneAI on ${new Date(project.created_at).toLocaleDateString()}\n\nOpen index.html in your browser to preview.`
    )

    const zipArrayBuffer = await zip.generateAsync({ type: 'arraybuffer', compression: 'DEFLATE' })
    const zipUint8 = new Uint8Array(zipArrayBuffer)

    const filename = `${project.name.replace(/[^a-zA-Z0-9-_]/g, '-')}.zip`

    return new NextResponse(zipUint8, {
      headers: {
        'Content-Type': 'application/zip',
        'Content-Disposition': `attachment; filename="${filename}"`,
        'Content-Length': zipUint8.length.toString(),
      },
    })
  } catch (err) {
    console.error('Download error:', err)
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 })
  }
}
