#!/usr/bin/env bash
# provision-ssl.sh — Provisions SSL certs for verified custom domains.
# Runs as a cron job every minute on the host server.
# Usage: crontab -e → add: * * * * * /usr/local/bin/provision-ssl.sh >> /var/log/provision-ssl.log 2>&1

set -euo pipefail

log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*"; }

# ── Load production env vars ─────────────────────────────────────────────────
ENV_FILE="/var/www/clone-app/.env.local"
if [ ! -f "$ENV_FILE" ]; then
  log "ERROR: $ENV_FILE not found"
  exit 1
fi

# shellcheck source=/dev/null
set -a
source "$ENV_FILE"
set +a

SUPABASE_URL="${NEXT_PUBLIC_SUPABASE_URL:-}"
SUPABASE_KEY="${SUPABASE_SECRET_KEY:-}"  # service role key

if [ -z "$SUPABASE_URL" ] || [ -z "$SUPABASE_KEY" ]; then
  log "ERROR: SUPABASE env vars not set"
  exit 1
fi

CERTBOT_WEBROOT="/var/www/certbot"
CERTBOT_EMAIL="admin@igualai.com"
NGINX_CONF_DIR="/etc/nginx/conf.d"

# Ensure webroot exists for ACME challenges
mkdir -p "$CERTBOT_WEBROOT"

# ── Query Supabase for verified-but-unprovisioned domains ────────────────────
RESPONSE=$(curl -sf \
  -H "apikey: ${SUPABASE_KEY}" \
  -H "Authorization: Bearer ${SUPABASE_KEY}" \
  "${SUPABASE_URL}/rest/v1/custom_domains?verified=eq.true&ssl_provisioned=eq.false&select=id,domain" 2>&1) || {
  log "ERROR: Supabase query failed: $RESPONSE"
  exit 1
}

# Parse JSON — extract id and domain pairs
PAIRS=$(echo "$RESPONSE" | python3 -c "
import sys, json
data = json.load(sys.stdin)
for d in data:
    print(d['id'] + '\t' + d['domain'])
" 2>/dev/null || true)

if [ -z "$PAIRS" ]; then
  exit 0  # Nothing to provision
fi

while IFS=$'\t' read -r domain_id domain; do
  [ -z "$domain_id" ] && continue

  log "Provisioning SSL for: $domain (id=$domain_id)"

  # ── Run certbot (webroot method) ────────────────────────────────────────
  if ! certbot certonly \
    --webroot \
    -w "$CERTBOT_WEBROOT" \
    -d "$domain" \
    --non-interactive \
    --agree-tos \
    -m "$CERTBOT_EMAIL" \
    --keep-until-expiring \
    2>&1; then
    log "WARN: certbot failed for $domain — skipping"
    continue
  fi

  CERT_PATH="/etc/letsencrypt/live/${domain}/fullchain.pem"
  KEY_PATH="/etc/letsencrypt/live/${domain}/privkey.pem"

  if [ ! -f "$CERT_PATH" ]; then
    log "WARN: cert not found at $CERT_PATH after certbot run — skipping"
    continue
  fi

  # ── Write per-domain nginx config ──────────────────────────────────────
  NGINX_CONF="${NGINX_CONF_DIR}/domain-${domain}.conf"
  cat > "$NGINX_CONF" << NGINXEOF
# Auto-generated by provision-ssl.sh — do not edit manually
server {
    listen 80;
    listen [::]:80;
    server_name ${domain};

    location /.well-known/acme-challenge/ {
        root ${CERTBOT_WEBROOT};
    }

    location / {
        return 301 https://\$host\$request_uri;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name ${domain};

    ssl_certificate ${CERT_PATH};
    ssl_certificate_key ${KEY_PATH};
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_cache_bypass \$http_upgrade;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header X-Forwarded-Host \$host;
    }
}
NGINXEOF

  # ── Test and reload nginx ───────────────────────────────────────────────
  if ! nginx -t 2>&1; then
    log "ERROR: nginx config test failed — removing bad config for $domain"
    rm -f "$NGINX_CONF"
    continue
  fi

  nginx -s reload
  log "nginx reloaded with HTTPS config for $domain"

  # ── Mark as provisioned in Supabase ────────────────────────────────────
  curl -sf -X PATCH \
    -H "apikey: ${SUPABASE_KEY}" \
    -H "Authorization: Bearer ${SUPABASE_KEY}" \
    -H "Content-Type: application/json" \
    -d '{"ssl_provisioned": true}' \
    "${SUPABASE_URL}/rest/v1/custom_domains?id=eq.${domain_id}" > /dev/null

  log "SSL provisioned successfully for $domain"

done <<< "$PAIRS"
